---
title: "Workshop3"
author: "Haseeb"
date: "8/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library (tidyverse)
library(skimr)

survey <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-05-18/survey.csv')

write_csv(survey,"survey_data.csv")

survey%>%glimpse()
survey%>%skim()

```

### Data Wrangling

### Filter

```{r}
survey_IT_au<-survey%>%
  filter(country=="Australia")

survey%>%
  filter(country=="Australia" | country=="australia")%>%
  filter(industry=="Computing or Tech" & annual_salary>80000)


```

#### Select

```{r}
survey_IT_au %>%
  select(how_old_are_you, job_title, annual_salary)

survey_IT_au%>%select(industry)
```


```{r}
library(tidyverse)
library(skimr)
library(lubridate)
```


```{r}
survey <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-05-18/survey.csv')
```


```{r}
survey <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-05-18/survey.csv')

survey_IT_au<-survey%>%
  filter(country=="Australia" | country=="australia"|country=="Australi")%>%
  filter(industry=="Computing or Tech" & annual_salary>80000)



```
```{r}
survey_IT_au%>%
  mutate(experience=parse_number(overall_years_of_professional_experience))
```

  
```{r}
survey <- survey %>%

  mutate(timestamp = mdy_hms(timestamp),

         age_category = fct_relevel(fct_reorder(how_old_are_you, parse_number(how_old_are_you)), "under 18"),

         experience_overall = str_replace(overall_years_of_professional_experience, " - ", "-"),

         experience_overall = fct_reorder(experience_overall, parse_number(experience_overall)),

         experience_in_field = str_replace(years_of_experience_in_field, " - ", "-"),

         experience_in_field = fct_reorder(experience_in_field, parse_number(experience_in_field))) %>%

  mutate(gender = fct_collapse(coalesce(gender, "Other or prefer not to answer"), "Other or prefer not to answer" = c("Other or prefer not to answer", "Prefer not to answer")),

         race = fct_lump(coalesce(race, "Other"), 4),

         age=parse_number(how_old_are_you))

 

survey_usd <- survey %>%

  filter(currency == "USD") %>%

  filter(annual_salary >= 5000,

         annual_salary <= 2e6) %>%

  mutate(state = str_remove(state, ", .*"))
```

